services:
  - type: web
    name: n8n-service
    env: node
    plan: free
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: 123456
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
